title: Feng Feng
logo: /assets/img/valley.png
description: I specialize in data analysis, statistical modeling, and data visualization using Python, R, SQL, and Tableau.
linkedin: http://www.linkedin.com/in/fengfengus/
theme: jekyll-theme-minimal #jekyll-theme-leap-day #jekyll-theme-hacker #Jekyll-theme-minimal
