title: Feng Feng
8+ years of experience in big data analysis using Python, R and SQL, with strong proficiency in statistical modeling, data visualization, and data manipulation.
theme: jekyll-theme-minimal #jekyll-theme-leap-day #jekyll-theme-hacker #Jekyll-theme-minimal
